"""Creator-center statistics import, analysis, and creative suggestions."""

from backend.services.creator_stats.analyze import (
    analyze_notes,
    as_fraction_engagement_rate,
    run_analysis,
)
from backend.services.creator_stats.client import (
    CREATOR_PROFILE_PATH,
    CREATOR_STATS_PAGE,
    CreatorStatsClient,
    CreatorStatsFetchError,
    FixtureTransport,
    normalize_period,
    period_to_date_type,
)
from backend.services.creator_stats.normalize import (
    extract_note_items,
    normalize_account_overview,
    normalize_account_profile,
    normalize_bundle,
    normalize_note,
    normalize_note_list,
)
from backend.services.creator_stats.pipeline import (
    import_bundle,
    sync_account_stats,
    sync_all_active_accounts,
    sync_from_fixture,
    sync_from_payload,
)
from backend.services.creator_stats.quality import (
    MIN_NOTES_FOR_OVERALL_SCORE,
    SCOPE_ALL_IMPORTED_HISTORY,
    analyze_historical_quality,
)
from backend.services.creator_stats.suggestions import (
    build_mode_creative_context,
    format_suggestions_context,
    get_suggestions_for_mode,
    suggestions_from_analysis,
)
from backend.services.creator_stats.types import (
    AccountStatsOverview,
    AnalysisResult,
    CreativeMode,
    CreativeSuggestion,
    CreatorQualityReport,
    CreatorStatsBundle,
    NoteStats,
    QualityConfidence,
    QualityDimension,
    QualityDimensionKey,
    QualityGrade,
    QualityInsight,
    QualityRecommendation,
    StyleFinding,
    SyncResult,
)

__all__ = [
    "CREATOR_PROFILE_PATH",
    "CREATOR_STATS_PAGE",
    "AccountStatsOverview",
    "AnalysisResult",
    "CreativeMode",
    "CreativeSuggestion",
    "CreatorQualityReport",
    "CreatorStatsBundle",
    "CreatorStatsClient",
    "CreatorStatsFetchError",
    "FixtureTransport",
    "NoteStats",
    "QualityConfidence",
    "QualityDimension",
    "QualityDimensionKey",
    "QualityGrade",
    "QualityInsight",
    "QualityRecommendation",
    "StyleFinding",
    "SyncResult",
    "analyze_notes",
    "analyze_historical_quality",
    "as_fraction_engagement_rate",
    "build_mode_creative_context",
    "format_suggestions_context",
    "get_suggestions_for_mode",
    "import_bundle",
    "sync_all_active_accounts",
    "MIN_NOTES_FOR_OVERALL_SCORE",
    "extract_note_items",
    "normalize_account_profile",
    "normalize_account_overview",
    "normalize_bundle",
    "normalize_note",
    "normalize_note_list",
    "normalize_period",
    "period_to_date_type",
    "run_analysis",
    "SCOPE_ALL_IMPORTED_HISTORY",
    "suggestions_from_analysis",
    "sync_account_stats",
    "sync_from_fixture",
    "sync_from_payload",
]
