export { default as SkeletonLoader } from '@/components/SkeletonLoader.vue'
export { default as MetricCardSkeleton } from './MetricCardSkeleton.vue'
export { default as ContentCardSkeleton } from './ContentCardSkeleton.vue'
export { default as DataTableSkeleton } from './DataTableSkeleton.vue'
export { default as DashboardSkeleton } from './DashboardSkeleton.vue'
export { default as AnalyticsSkeletonComponent } from './AnalyticsSkeleton.vue'
export { default as ReviewSkeletonComponent } from './ReviewSkeleton.vue'
export { default as HomeSkeleton } from './HomeSkeleton.vue'
export { default as EvaluationSkeleton } from './EvaluationSkeleton.vue'
export { default as ShowcaseSkeleton } from './ShowcaseSkeleton.vue'
export { default as ReplaySkeleton } from './ReplaySkeleton.vue'

// Convenience wrapper components (using proper Vue SFC instead of string templates)
export { default as ReviewSkeleton } from './ReviewSkeletonWrapper.vue'
export { default as AnalyticsSkeleton } from './AnalyticsSkeletonWrapper.vue'